### ISSUE TITLE
Push switches are difficult to select

### ISSUE THREAD

**Issue by zachdaniel** [kahole/edamagit#15]
in magit on emacs, I type `p` `-` `f` `u` and it does a force with lease push to origin. I think its okay if I have to do it differently in magit for vscode, but I think the typeahead search should perhaps be tweaked to:

1.) not search the descriptions
2.) be case sensitive (maybe?)

I've added a screenshot of what I see when I type `-f` to select a switch.

![Screen Shot 2020-03-27 at 2 20 04 PM](https://user-images.githubusercontent.com/5722339/77787709-63046a00-7036-11ea-999e-addce8f34b79.png)

This requires me to type more or select it with my arrow keys. Although, it looks like the arrow keys are always necessary, since I have to go down one to select my desired switch. Would be nice to eliminate that some how.

**Comment by kahole** [comment]
@zachdaniel 
I'm not content with the switches menu either.
I've experimented with enabling switches with a single keypress, like your example `P - f`
And gotten it to work fine, when your eyes are closed.
(see commit above)

Problem being that even though I clear the filter text field as the user types, it still narrows down the options, and doesn't update until another key-event.

<img width="725" alt="Screenshot 2020-04-16 at 23 36 10" src="https://user-images.githubusercontent.com/9072087/79509396-bb2dfb00-803b-11ea-8b2b-ba3b9183e912.png">
<img width="726" alt="Screenshot 2020-04-16 at 23 36 26" src="https://user-images.githubusercontent.com/9072087/79509422-c4b76300-803b-11ea-8351-ca61319edb6f.png">

This idea for the switches UI might have run its course. I'm open for new ones.
