### ISSUE TITLE
Commit fails on VSCodium

### ISSUE THREAD

**Issue by gabriel4649** [kahole/edamagit#25]
Hey!

Emacs immigrant here xD

Thanks for making this. It makes me feel less homesick at VSCode.

I'm using [VSCodium](https://github.com/VSCodium/vscodium), which is exactly the same as VSCode except without the Microsoft stuff. 

Commit fails out of the box, because of the binary name reference. 

```
"/usr/share/vscodium-bin/bin/code" --wait: /usr/share/vscodium-bin/bin/code: No such file or directory
error: There was a problem with the editor '"/usr/share/vscodium-bin/bin/code" --wait'.
Please supply the message using either -m or -F option.
```
The binary name on VSCodium is `codium`, instead of `code`. 

For future VSCodium users, perhaps you can take this into account in your code.

Best regards,
Gabriel

**Comment by kahole** [comment]
It seems in macOS it's still named 'code' for VSCodium.
```
❯ pwd
/Applications/VSCodium.app/Contents/Resources/app/bin
❯ ll | grep -i cod
-rwxr-xr-x@ 1  1329727921   484B May  8 13:04 code
```
So the fix is quite ugly and is prone to breaking it seems, but I it will do for now.

Can you confirm that it works? :)

**Comment by gabriel4649** [comment]
That works! Thanks
