### ISSUE TITLE
Quick menu alignment

### ISSUE THREAD

**Issue by stevenguh** [kahole/edamagit#27]
Your quick menu inspired me to write a spacemacs like menu in VSCode with Vim. While working on it and I realized that if a tab is added in front of the description text for QuickPick, the description of item in the QuickPick menu will be aligned.

Before:
![Before](https://user-images.githubusercontent.com/3455662/82173644-d716fd80-9882-11ea-8c12-cf8b05da0e4f.png)

After:
![After](https://user-images.githubusercontent.com/3455662/82173659-df6f3880-9882-11ea-9bcb-cf4f99c72c4b.png)

I have a menu class that makes it easier to add tab without adding tab character everywhere in code. I can help implement that here if you think that pattern is applicable here as well.

**Comment by kahole** [comment]
Nice find, makes it a lot tidier and clearer. Thank you 👍
