### ISSUE TITLE
When commit message opens, the cursor does not position itself in the beginning of the buffer

### ISSUE THREAD

**Issue by vmalloc** [kahole/edamagit#28]
Not sure how to reproduce but this started happening to me without any change on my part that I can remember

**Comment by kahole** [comment]
VSCode has a setting for this that is on by default:
```"workbench.editor.restoreViewState": true```
Set it to false and all documents will open with the cursor on top.

Sadly, this is not possible to set per language. (e.g. only for `git-commit` language)
So it'll have to be done some other way, gonna look into it.

**Comment by vmalloc** [comment]
Thanks! Much appreciated!

**Comment by kahole** [comment]
Quick explanation for removing the fix:
The fix for this set the cursor to the beginning of the buffer every time the user changed focus to the commit message editor, which is not acceptable.
