### ISSUE TITLE
Add support for interactive rebasing

### ISSUE THREAD

**Issue by vmalloc** [kahole/edamagit#29]
Perhaps this is already supported but could not figure out how to actually do it.

Thanks for this amazing project!

**Comment by stevenguh** [comment]
I think this is supported with the `i` option in rebase; however, it uses the quick menu API to select instead of the file view.

**Comment by vmalloc** [comment]
Oh! that's correct. I wasn't seeing anything because I chose to rebase on an already-rebased branch 🤦 
Sorry for being an idiot!
