### ISSUE TITLE
Graph in Logging

### ISSUE THREAD

**Issue by stevenguh** [kahole/edamagit#38]
Graph is one of the features I really want. Since the built-in api for logging is so limiting, I am thinking this will probably run raw git log with [custom format](https://git-scm.com/docs/pretty-formats) and capture the output and parse it with regex. I think this work will lay the foundation for many other features that rely on logs. 

I think this is probably on your radar. I am just wondering is there any room for collaborator to help?

**Comment by kahole** [comment]
I haven’t gotten around to logging yet
A lot is missing, and I really don’t know too much about git logging tbf.
This area is wide open for contributions 😃

**Comment by stevenguh** [comment]
I can take a stab at it😊I just didn't want to duplicate any existing effort.
