### ISSUE TITLE
Cannot execute magit.status because there is no active text editor.

### ISSUE THREAD

**Issue by roblabla** [kahole/edamagit#44]
Currently, if one opens a folder and runs "> Magit Status" without opening a text editor, the command will silently no-op, and the message `Cannot execute magit.status because there is no active text editor.` will appear in the Extension Host output window.

The command should still work in this situation, or, if that's not possible for some reason, show a user-visible warning that an editor needs to be open before running the command.

**Comment by kahole** [comment]
A workspace doesn't always equate to a single git-repository, and activeWorkspaces is a list, thats why it's like this. And the command is only available when there is an active text editor. So the lack of feedback when a keybinding attempts an unavailable command is more of a VSCode issue, but we can fix it here :)

Would the 'Which repository?'-prompt suffice (the one that pops up when you're editing a file outside of a git repository), or should edamagit do rather try to find the best candidate?
Let me know what you think.

**Comment by roblabla** [comment]
Well, at the very least there needs to be feedback.

Maybe we can make it a bit smart: if there is only a single workspace active and it has a repo at the root, use that, otherwise prompt the user. That would simplify the common case, while still properly handling the edge cases.

**Comment by kahole** [comment]
Yeah, sorry, gitApi repositories can be more than one in a single workspace.

**Comment by oo6** [comment]
@kahole  I'm glad that issue is solved, thank you!

Can allow `magit.dispatch` from anywhere? And remove the `when` clause of `magit.status` and `magit.dispatch` in commandPalette?
I'd be happy to contribute.

**Comment by kahole** [comment]
Yes, those changes should be made as well.
@oo6
