### ISSUE TITLE
How to interactively rebase against master?

### ISSUE THREAD

**Issue by jackfranklin** [kahole/edamagit#48]
Hey,

Firstly, thank you for this plugin! I'm really enjoying using it and it's become my main tool for Git whilst working.

I think this might be me misunderstanding the plugin (I'd be happy to contribute docs) but I'm struggling to figure how to do an interactive rebase. Quite often whilst on a branch I'll do `git rebase -i main` to choose which commits to reword/squash etc.

Firstly, it would be great if when kicking off a rebase it would show branches as well as commits, or at least show that in the UI, so it's easier to pick, say "the HEAD of master" to rebase against.

After that I'm able to see a UI that edamagit shows me to chose which commits to pick/fixup/squash/etc, but when I then save that I don't know what to do next. I'm clearly mid-rebase but I get confused on what to do to walk through each of those commits and edit them. Would you mind clarifying the process/pointing me in the right direction? I think I'm probably missing something obvious but I can't figure it.

Thank you!

Jack

**Comment by kahole** [comment]
Thanks for your feedback. I think you raise an important issue. The problem of how this extension is to get into for people who aren't familiar with Magit in Emacs. (the plugin this extension tries to emulate).
That's how I read it anyway, not sure if thats accurate in your case.

What can look like odd choices in this VSCode extension have been made to closely emulate Magit Emacs behaviour, using a different set of tools and APIs. This makes the UI a little non-intuitive in certain cases. E.g the single key activation of an action in the menus for rebase, branching, etc.

Also, there are no docs or tutorials for this extension. Right now the users are expected to know either Magit or read the docs for it (https://magit.vc/)

It would be great to have docs/help for edamagit as well.

--

To try and help you with your specific issue:

> Firstly, it would be great if when kicking off a rebase it would show branches as well as commits, or at least show that in the UI, so it's easier to pick, say "the HEAD of master" to rebase against.

You should try to activate the interactive switch and do rebase "onto elsewhere". (this will give you branches to choose from.)
You turn on the interactive switch by pressing `-` from the rebase menu to get into the switches menu, then `i` to activate `--interactive` switch, and then enter to return to rebase menu which now will apply the switch when pressing `e  onto elsewhere`.


> After that I'm able to see a UI that edamagit shows me to chose which commits to pick/fixup/squash/etc, but when I then save that I don't know what to do next.

Saving and exiting starts the rebase, yes. (shortcut `ctrl+c ctrl+c`)
I'm not entirely sure what you need here, but pressing `r` from the status view again will bring up the 'controls' for the ongoing rebase, i.e 'Continue', 'Edit', 'Abort'.

Let me know if that works for you.

**Comment by jackfranklin** [comment]
Thanks for your help! I just tried those steps and I think it's working.

However, once starting the rebase, if I've picked to reword a commit, I'd expect a Magit window to open with that commit so that I can reword it. I'm not seeing that (I just got to it manually via `commit -> amend`. I'm not sure if this is the expected behaviour or if it's a bug (my lack of familiarity with Magit!). 

What is the expected behaviour with this plugin and editing commits as part of a rebase? If this is a bug I'm happy to dig in and try to figure out what's going wrong.

**Comment by jackfranklin** [comment]
Looking at the magit process log it looks like it might be trying to defer the rebase to Vim (which I have set as my git $EDITOR - maybe that's causing problems?)

```
git rebase --interactive main
Rebasing (1/1)
Vim: Error reading input, exiting...

Vim: Finished.
error: There was a problem with the editor 'nvim -u $HOME/.config/nvim/git-init.vim'.
Please supply the message using either -m or -F option.
You can amend the commit now, with

  git commit --amend 

Once you are satisfied with your changes, run

  git rebase --continue
```

**Comment by kahole** [comment]
That looks like a bug.
When executing such a command we provide an $EDITOR reference to vscode itself in order to edit the message.


‘runCommitLikeCommand’

**Comment by kahole** [comment]
Looks like we need to supply both GIT_EDITOR _and_ GIT_SEQUENCE_EDITOR to environment of `git rebase --interactive main`, to get this working properly.
Also the rebase-continue command, in case there is a conflict or holdup.
Might be an easy fix, or need some restructured approach...

**Comment by kahole** [comment]
The commit above should fix the immeadiate problem of not being able to reword while rebasing interactively.

Outstanding issue:
If there is a conflict and you 'Rebasing Continue' later, it will not allow you to reword without you selecting the 'Rebasing Edit' to continue the rebase.
I assume the original choice of 'reword' should be respected on continuation as well, although I have not confirmed this.

**Comment by jackfranklin** [comment]
@kahole I will give 0.2.5 a go, thank you!

**Comment by jackfranklin** [comment]
0.2.5 does indeed fix the flow, thank you!
