### ISSUE TITLE
Crash on Mac with Insiders build when committing

### ISSUE THREAD

**Issue by jackfranklin** [kahole/edamagit#49]
Committing causes a Magit crash (the commit window opens and immediately closes). I managed to reproduce it locally and get the error which is:

```
git commit
"/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code-insiders" --wait: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code-insiders: No such file or directory
error: There was a problem with the editor '"/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code-insiders" --wait'.
Please supply the message using either -m or -F option
```

I'm not sure what the issue is but what I did notice is that locally there is no `app/bin/code-insiders` - it's still just `app/bin/code` even though it's in the `Insiders.app`. If I remove the code that adds `-insiders` it passes; but I think we might need that code for Windows and/or Linux. In which case we could make that line conditional on being not Mac? E.g.:

```
    if (isInsiders && !isDarwin) {
      codePath += '-insiders';
    }
```

If you think that looks right let me know, I'd be happy to contribute the fix.

Thanks!

**Comment by kahole** [comment]
Yes, that should do the trick.
Please do make a PR :)
