### ISSUE TITLE
installed extension collision with EditorConfig (VSCodium)

### ISSUE THREAD

**Issue by waymondo** [kahole/edamagit#52]
First of all, thank you so much. Magit is the one Emacs package I have truly missed since I began exploring the world of VS. I'm amazed at how well this is working so far!

Here are the steps that produce the issue I'm seeing (I'm on VSCodium fwiw):

* Open VSCodium (Edamagit is not installed, EditorConfig is not installed)
* Install extension from VSIX file
* At this point, Edamagit works in all currently open workspaces
* If I open a new workspace and try to run "Magit Status" I get the error message `command 'magit.status' not found`
* When I look at my installed extensions I don't see Edamagit.
* If I try to re-install from the VSIX file I get the error message `Please reload Visual Studio Code to complete installing the extension EditorConfig for VS Code.`
* If I restart VSCodium, all current and future workspaces are in the described state where EditorConfig is installed and the magit commands and extension aren't found.
* If I uninstall EditorConfig, restart VSCodium, and re-install Edamagit from the VSIX file, it works again (for open workspaces).

**Comment by kahole** [comment]
I have never tried EditorConfig, do they do anything weird in their setup?

I have attempted making `edamagit` be a 'good citizen' in the vscode world. Let me know if there is something that has been done wrong in this sense.

**Comment by waymondo** [comment]
The weird thing is I don't have EditorConfig installed before installing Edamagit. Did a bit of searching and it looks like a VSCodium-specific problem: https://github.com/VSCodium/vscodium/issues/434. I'll close since it seems not specific to Edamagit, sorry for the noise!
