### ISSUE TITLE
Commit opening in new VSCode window

### ISSUE THREAD

**Issue by jackfranklin** [kahole/edamagit#60]
I'm not sure what's changed - if it's a change in VSCode, or in this plugin, but as of today when I commit using this plugin rather than open the commit editor in a new tab/pane in my existing VSCode window, it now opens up an entirely new VSCode window.

I'd rather have it not do this and use the existing window; although I can imagine others might think differently. Is it possible to make this configurable?

**Comment by jackfranklin** [comment]
Thinking about it, this might be as I just updated to the newest version of VSCode (1.47.2). I don't think the latest releases of this plugin contain any relevant changes. I can't be 100% sure though.

**Comment by kahole** [comment]
I'm not able to reproduce this on my mac with 'normal' VSCode 1.47.2.
What platform are you on? And what variant of VSCode? (code/codium/insider)
Lastly, do you have any VSCode settings for git/window management, or anything that could be related to this? :)

**Comment by jackfranklin** [comment]
Today I quit Code and re-opened it and it is now fixed. I'm not sure why/what caused it, but I'll close this for now and shout if it occurs again!
