### ISSUE TITLE
Problems with submodules

### ISSUE THREAD

**Issue by Nebucatnetzer** [kahole/edamagit#63]
edamagit seems to have problems with submodules.
When I open a file from the submodule and open edamagit it's still stuck in the parent repository.

**Comment by kahole** [comment]
Ah, this probably has to do with the way repositories are selected (file sub path). Will look into it soon.
Submodule command support is on the roadmap as well.

**Comment by Nebucatnetzer** [comment]
Thanks that would be great, however no stress.
It's already great as it is, magit is the one thing which keeps bringing me back to Emacs besides org mode.
However I with your plugin I can use Emacs simply for org mode and use VSCode for coding.
