### ISSUE TITLE
Help text failed to read when keybindings have trailing commas

### ISSUE THREAD

**Issue by stevenguh** [kahole/edamagit#64]
I am not sure if we talked about this a while back. The help text reader doesn't work if the last property of the json contains trailing commas.

For example, if there is a commas after `"-magit.discard-at-point"`, which vscode will happily read that. But the comments striping process doesn't remove the trailing commas which causes `JSON.parse` to failed because trailing commas on object is not valid json.

example: keybindings.json:
```jsonc
{
	{
		"key": "k",
		"command": "-magit.discard-at-point",
	},
}
```

**Comment by kahole** [comment]
Yes, this file should be cleaned up or parsed using a lib.

**Comment by stevenguh** [comment]
Internally in vscode, they uses `jsonc-parser` in multiple places, that might be one option.
