### ISSUE TITLE
"undefined" in -n option

### ISSUE THREAD

**Issue by stevenguh** [kahole/edamagit#74]
First of all, thank you for implementing the option with input box 👍 I somehow happened to see your update and tested it, and found a bug and just want to let you know if you are not aware.

Steps to repo:
1. Open up the logging quick pick (`l`)
2. Press `=` to open up option
3. Press `n` to cancel the option selection
4. Press `enter` to cancel out
5. Press `=` to enter options again
6. ![image](https://user-images.githubusercontent.com/3455662/92028659-4244ec80-ed19-11ea-8377-21e3455eebda.png)

**Comment by kahole** [comment]
Thanks. Fixed in ^ commit.
Only a visual bug, so it will be included in the next release.

**Comment by kahole** [comment]
Which is immediately now. :P (I found a bigger issue)
