### ISSUE TITLE
relation between the different buffers can get mixed up

### ISSUE THREAD

**Issue by grozan** [kahole/edamagit#76]
Hi,

discovered edamagit today and I love it, thanks a lot for that!
playing around with it, I see some strange behaviour sometimes.
Not the easiest to describe, but I'll do my best.

Say you have 2 git repos opened in the workspace: repo1 and repo2
Open one file of each repo
I focus on repo1/file1, magit status, press ENTER on some recent commits, display the git log and enter some commits. everytime I exit the buffer that just opened with `q`. Finally quit magit status with `q`. I do it again.
I focus on repo2/file2 and do the same thing
I focus on repo1/file1 again, and continue.
And so on

Very quickly (like in less than 20 seconds for me) I will see the problem happening.
It can be of 2 different kinds:

case1: I focus on repo1/file1, magit status, display the log, and there I see the history of repo**2** instead of mine. When I hit `q` I see also the magit-status page of repo2, instead of mine

case2: I focus on repo1/file1, magit status. If I have unstaged changes, for example, I see the list of modified files, all good. But now the TAB key does not do anything anymore. Instead of displaying the modified chunks, like it does normally, it does nothing at all. I cannot stage/unstage files either. I cannot interact with anything anymore, in that magit status buffer. The only indication is (only sometimes) the message "There is no thing at point that could be visited" in the status bar

When the problem happens (either way, case1 or case2), the only way to get magit to function normally again is to reload the vscode window.

Hopefully my description is understandable enough and you can reproduce it

**Comment by kahole** [comment]
I'm able to reproduce the issue. There is indeed an issue with two repos (non-sub repo) in the same workspace.
Working on fix, thanks for reporting 👍

**Comment by kahole** [comment]
0.4.7 with fix now published. Let me know whether it works :)

**Comment by grozan** [comment]
Hi, I can't reproduce the problem anymore, looks great. Thanks!
