### ISSUE TITLE
Pull --rebase option?

### ISSUE THREAD

**Issue by stevenguh** [kahole/edamagit#77]
I am wondering can we implement --rebase option for pulling. https://github.com/kahole/edamagit/blob/b0e5d958e981de54f0d5855887a6eec55b6a2146/src/commands/pullingCommands.ts#L25-L40
It seems like we just need to add the argument as part of the command in `pullFromPushRemote` and `pullFromUpstream`. However, I am not sure about `pullFromElsewhere`

**Comment by kahole** [comment]
I wanna move away from using "executeCommand" and existing git vscode commands for this reason. They are not flexible enough.
So we should just replace it with a prompt and gitRun ...['pull', ...] etc
