### ISSUE TITLE
, . < > ' legends in Help menu

### ISSUE THREAD

**Issue by EPonyA** [kahole/edamagit#79]
![image](https://user-images.githubusercontent.com/1811218/95028658-cfa89300-066f-11eb-849d-4732121cfa56.png)

I was configuring the keybindings to prevent conflicts with my Dvorak modal editing bindings, and I noticed that , . < > and ' are being displayed as oem_comma oem_period OEM_COMMA OEM_PERIOD and oem_7 respectively. I didn't notice an issue regarding this posted yet.

**Comment by kahole** [comment]
Would you mind posting the relevant section of your `keybindings.json`? :)

**Comment by EPonyA** [comment]
I think I've reconfigured somewhat, but this is essentially very similar.
```
[
	{
		"key": "oem_semicolon",
		"command": "magit.branching",
		"when": "editorTextFocus && editorLangId == 'magit' && vim.mode =~ /^(?!SearchInProgressMode|CommandlineInProgress).*$/"
	},
	{
		"key": "oem_period",
		"command": "magit.merging",
		"when": "editorTextFocus && editorLangId == 'magit' && vim.mode =~ /^(?!SearchInProgressMode|CommandlineInProgress).*$/"
	},
	{
		"key": "shift+oem_period",
		"command": "magit.rebasing",
		"when": "editorTextFocus && editorLangId == 'magit' && vim.mode =~ /^(?!SearchInProgressMode|CommandlineInProgress).*$/"
	},
	{
		"key": "oem_7",
		"command": "magit.stashing",
		"when": "editorTextFocus && editorLangId == 'magit' && vim.mode =~ /^(?!SearchInProgressMode|CommandlineInProgress).*$/"
	},
	{
		"key": "shift+oem_comma",
		"command": "magit.reverting",
		"when": "editorTextFocus && editorLangId == 'magit' && vim.mode =~ /^(?!SearchInProgressMode|CommandlineInProgress).*$/"
	},
	{
		"key": "oem_comma",
		"command": "magit.reverse-at-point",
		"when": "editorTextFocus && editorLangId == 'magit' && vim.mode =~ /^(?!SearchInProgressMode|CommandlineInProgress).*$/"
	}
]
```

Lol and it just occurred to me that I can simply put the actual symbols in there instead. That largely fixes the issue, but there is a matter of highlighting.
![image](https://user-images.githubusercontent.com/1811218/95249610-f0472900-07e6-11eb-8bd7-40390899271a.png)

Interestingly, the highlighting works great when the legend is preceded by 'shift+'.
