### ISSUE TITLE
For MagitUtil confirm dialogs, can we get rid of the need to press the "Enter" key after the user types 'y' or 'n'?

### ISSUE THREAD

**Issue by yongwangd** [kahole/edamagit#80]
I came to vscode from spacemacs/magit. I have been using this plugin for a few hours and it's simply **amazing**!

At this moment, for any 'Y/N' confirm dialog, I have to press "Enter" key after I typed in 'y' or 'n', whereas in emacs, I don't need to press "Enter", emacs-magit will perform the confirm action as long as I type 'y'. **Can we get rid of the need to press the "Enter" key after the user types 'y' or 'n'?** 

 **I can submit a PR if we think it helps.**

<img width="892" alt="Screenshot_2020-10-07 16 30 24_ElriqK" src="https://user-images.githubusercontent.com/5342062/95384558-ca8b5400-08ba-11eb-8a8f-ae7c541ec084.png">

**Comment by kahole** [comment]
Cheers!

I have this lying around actually 410582575da8d898da53cc4930eff5a3580fc63c
Although, I'm not entirely convinced it's the right way to go, even though it's closer to how Magit does it.

**Comment by kahole** [comment]
The reason I'm unsure is that I haven't found a way to remove "Press (Enter) to confirm" from the dialog. Meaning when a user types 'y' they might be surprised to see it complete. And the dialog is, of course, only used for destructive actions which makes it important to make sure the user actually wants to perform it.

**Comment by yongwangd** [comment]
I think probably 100% of the users of this plugin come from Emacs, and we all very used to the y/n confirm dialog emacs/magit provides. All, if at least we can make this option configurable, defaulting to that users have to press enter, and they can also config it to just confirm w/o pressing "Enter".

Anyway, really awesome job on this plugin. I don't need to open emacs just to do git stuff any more 👍

**Comment by stevenguh** [comment]
> I haven't found a way to remove "Press (Enter) to confirm" from the dialog.

Using a QuickPick without any menu item can probably remove those built-in text

**Comment by stevenguh** [comment]
Just want to say, the new confirm dialog looks and works perfectly. Thanks :)
